---
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

install: true

script: ./scripts/ci/build.sh

deploy:
  provider: script
  script: ./scripts/ci/docker_push.sh
  on:
    branch: master
